"""Deterministic Financial Math & Forensic Audit Tools.

Enforces Architectural Principle #2: Zero Mathematical Hallucination.
Computes multi-year profitability, cash flow, solvency, and capital return metrics
(including ROIC with derived effective tax rate and consistent liquid cash treatment),
and performs sequenced algorithmic forensic accounting red-flag checks.
"""

import logging
import math
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field, AliasChoices, field_validator
from langchain_core.tools import tool

logger = logging.getLogger("finance_agent.tools.financial_math")


# ==============================================================================
# 1. Input Schemas with Pydantic Field Aliases (Agent Ergonomics)
# ==============================================================================
class AnnualFinancialInput(BaseModel):
    """
    Extracted annual financial data for a single fiscal year.
    Equipped with AliasChoices to accept standard US-GAAP / 10-K synonyms.
    """
    fiscal_year: int = Field(
        ...,
        description="4-digit fiscal year (e.g. 2025)",
        validation_alias=AliasChoices("fiscal_year", "year", "fy")
    )
    revenue: float = Field(
        ...,
        description="Total net sales or revenues in $ millions",
        validation_alias=AliasChoices("revenue", "total_revenue", "net_sales", "total_net_sales", "sales")
    )
    gross_profit: float = Field(
        ...,
        description="Gross profit / gross margin in $ millions",
        validation_alias=AliasChoices("gross_profit", "gross_margin", "gross_income")
    )
    operating_income: float = Field(
        ...,
        description="Operating income / EBIT in $ millions",
        validation_alias=AliasChoices("operating_income", "ebit", "operating_profit", "income_from_operations")
    )
    net_income: float = Field(
        ...,
        description="Net income attributable to common shareholders in $ millions",
        validation_alias=AliasChoices("net_income", "net_earnings", "net_profit")
    )
    operating_cash_flow: float = Field(
        ...,
        description="Net cash generated by operating activities in $ millions",
        validation_alias=AliasChoices(
            "operating_cash_flow",
            "cash_from_operations",
            "operating_activities_cash_flow",
            "cash_provided_by_operating_activities",
            "net_cash_provided_by_operating_activities"
        )
    )
    capital_expenditures: float = Field(
        ...,
        description=(
            "Capital expenditures (CapEx / additions to property, plant & equipment) in $ millions. "
            "Must be passed as a positive magnitude representing cash outflows."
        ),
        validation_alias=AliasChoices(
            "capital_expenditures",
            "capex",
            "payments_for_acquisition_of_property_plant_and_equipment",
            "purchases_of_property_and_equipment",
            "additions_to_property_plant_and_equipment"
        )
    )
    # Secondary / Optional line items for tax derivation and forensic analysis
    pretax_income: Optional[float] = Field(
        None,
        description="Income before provision for income taxes in $ millions",
        validation_alias=AliasChoices(
            "pretax_income",
            "income_before_taxes",
            "income_before_provision_for_income_taxes",
            "income_before_income_tax",
            "earnings_before_taxes"
        )
    )
    income_tax_expense: Optional[float] = Field(
        None,
        description="Provision for income taxes / tax expense in $ millions",
        validation_alias=AliasChoices(
            "income_tax_expense",
            "provision_for_income_taxes",
            "tax_expense",
            "income_tax_provision"
        )
    )
    depreciation_amortization: Optional[float] = Field(
        None,
        description="Depreciation and amortization expense in $ millions (for EBITDA)",
        validation_alias=AliasChoices(
            "depreciation_amortization",
            "depreciation_and_amortization",
            "dna",
            "depreciation"
        )
    )
    accounts_receivable: Optional[float] = Field(
        None,
        description="Net accounts receivable in $ millions (for Tier 2 forensic check)",
        validation_alias=AliasChoices("accounts_receivable", "ar", "accounts_receivable_net")
    )
    inventories: Optional[float] = Field(
        None,
        description="Total inventory in $ millions (for Tier 3 forensic check; omit if N/A)",
        validation_alias=AliasChoices("inventories", "inventory")
    )

    @field_validator("capital_expenditures")
    @classmethod
    def validate_capex_positive(cls, v: float) -> float:
        """
        Safety guard: Rejects negative CapEx values.
        Enforces consistency with Zero Mathematical Hallucination: CapEx must be passed
        as a positive magnitude representing cash outflows (e.g. 12715.0, not -12715.0).
        Prevents misreading asset sale proceeds as CapEx or silent sign masking.
        """
        if v < 0:
            raise ValueError(
                f"capital_expenditures ({v:,.2f}) must be passed as a positive magnitude "
                f"representing cash outflows (e.g. 12715.0 instead of -12715.0). "
                f"If this line item represents proceeds from asset sales, do not pass it as CapEx."
            )
        return float(v)


class BalanceSheetInput(BaseModel):
    """
    Extracted balance sheet snapshot for the latest fiscal year.
    Equipped with validation guard on diluted shares to prevent scale errors.
    """
    fiscal_year: int = Field(
        ...,
        description="4-digit fiscal year of the balance sheet (e.g. 2025)",
        validation_alias=AliasChoices("fiscal_year", "year", "fy")
    )
    cash_and_equivalents: float = Field(
        ...,
        ge=0.0,
        description="Cash and cash equivalents in $ millions",
        validation_alias=AliasChoices("cash_and_equivalents", "cash", "cash_and_cash_equivalents")
    )
    marketable_securities: float = Field(
        0.0,
        ge=0.0,
        description="Total liquid marketable securities (current + non-current liquid holdings) in $ millions",
        validation_alias=AliasChoices("marketable_securities", "short_term_investments", "liquid_investments")
    )
    short_term_debt: float = Field(
        0.0,
        ge=0.0,
        description="Commercial paper, current portion of long-term debt, and short-term borrowings in $ millions",
        validation_alias=AliasChoices(
            "short_term_debt",
            "commercial_paper",
            "current_debt",
            "current_portion_of_debt",
            "current_portion_of_term_debt"
        )
    )
    long_term_debt: float = Field(
        0.0,
        ge=0.0,
        description="Non-current term debt and long-term borrowings in $ millions",
        validation_alias=AliasChoices("long_term_debt", "term_debt", "non_current_debt")
    )
    stockholders_equity: float = Field(
        ...,
        description="Total stockholders' / shareholders' equity in $ millions (can be negative)",
        validation_alias=AliasChoices("stockholders_equity", "shareholders_equity", "total_equity", "equity")
    )
    diluted_shares_outstanding: float = Field(
        ...,
        description="Diluted common shares outstanding in MILLIONS (e.g. 15004.7, NOT 15004697 or 15004697000)",
        validation_alias=AliasChoices("diluted_shares_outstanding", "diluted_shares", "shares_outstanding")
    )
    current_assets: Optional[float] = Field(
        None,
        ge=0.0,
        description="Total current assets in $ millions (for Current Ratio)",
        validation_alias=AliasChoices("current_assets", "total_current_assets")
    )
    current_liabilities: Optional[float] = Field(
        None,
        ge=0.0,
        description="Total current liabilities in $ millions (for Current Ratio)",
        validation_alias=AliasChoices("current_liabilities", "total_current_liabilities")
    )

    @field_validator("diluted_shares_outstanding")
    @classmethod
    def validate_shares_scale(cls, v: float) -> float:
        """
        Safety guard: Rejects share counts passed in thousands or raw units (> 100,000).
        Enforces user direction: Do not silently auto-normalize; guide the caller explicitly.
        """
        if v > 100_000.0:
            raise ValueError(
                f"diluted_shares_outstanding ({v:,.2f}) appears to be passed in thousands or raw units. "
                f"All shares must be standardized to MILLIONS (e.g. 15004.7 instead of 15004697). "
                f"Please divide by 1,000 (or 1,000,000) and retry."
            )
        if v <= 0:
            raise ValueError(f"diluted_shares_outstanding must be strictly positive (> 0), got: {v}")
        return float(v)


# ==============================================================================
# 2. Structured Output Schemas
# ==============================================================================
class YearFinancialsResult(BaseModel):
    """Calculated metrics for a single fiscal year."""
    fiscal_year: int
    revenue: float
    gross_profit: float
    gross_margin_pct: float
    operating_income: float
    operating_margin_pct: float
    net_income: float
    net_margin_pct: float
    operating_cash_flow: float
    capital_expenditures: float
    free_cash_flow: float
    fcf_conversion_pct: Optional[float] = None
    revenue_growth_pct: Optional[float] = None
    operating_income_growth_pct: Optional[float] = None
    fcf_growth_pct: Optional[float] = None


class BalanceSheetResult(BaseModel):
    """Calculated balance sheet and liquidity bridge."""
    fiscal_year: int
    cash_and_equivalents: float
    marketable_securities: float
    total_liquid_cash: float
    short_term_debt: float
    long_term_debt: float
    total_debt: float
    net_debt: float
    net_cash_position: bool
    stockholders_equity: float
    diluted_shares_outstanding: float
    current_assets: Optional[float] = None
    current_liabilities: Optional[float] = None


class ProfitabilityRatiosResult(BaseModel):
    """Profitability, margin, and capital efficiency ratios."""
    effective_tax_rate_pct: float
    tax_rate_source: str
    equity_status: str = Field(
        "positive_book_equity",
        description="Status of book equity: positive_book_equity, negative_book_equity_ratios_suppressed, or zero_book_equity_ratios_suppressed"
    )
    nopat: float
    invested_capital: float
    roic_pct: Optional[float] = None
    roe_pct: Optional[float] = None
    latest_gross_margin_pct: float
    latest_operating_margin_pct: float
    latest_net_margin_pct: float


class SolvencyRatiosResult(BaseModel):
    """Solvency, leverage, and liquidity ratios."""
    net_debt_to_ebitda: Optional[float] = None
    net_debt_to_ebitda_interpretation: str
    current_ratio: Optional[float] = None
    total_debt_to_equity: Optional[float] = None


class FinancialAuditResult(BaseModel):
    """Complete structured output returned by audit_financial_metrics."""
    multi_year_history: List[YearFinancialsResult]
    balance_sheet: BalanceSheetResult
    profitability_and_return_ratios: ProfitabilityRatiosResult
    solvency_and_liquidity_ratios: SolvencyRatiosResult
    forensic_red_flags: List[str]


# ==============================================================================
# 3. Input Validation Helper
# ==============================================================================
def _validate_finite_number(val: Any, name: str) -> float:
    """Validates that a numeric argument is a real, finite float."""
    if val is None:
        raise ValueError(f"{name} cannot be None.")
    if not isinstance(val, (int, float)) or math.isnan(val) or math.isinf(val):
        raise ValueError(f"{name} must be a valid finite number, got: {val}")
    return float(val)


# ==============================================================================
# 4. Internal Function 1: Financial Ratios Calculation
# ==============================================================================
def calculate_financial_ratios(
    annual_financials: List[AnnualFinancialInput],
    balance_sheet: BalanceSheetInput,
) -> Dict[str, Any]:
    """
    Computes multi-year margins, Free Cash Flow, YoY growth rates, effective tax rate,
    ROIC, ROE, Net Debt, and solvency ratios from verified line items.
    Enforces contiguous fiscal years and temporal matching with the balance sheet.
    """
    if not annual_financials:
        raise ValueError("annual_financials must contain at least one fiscal year.")

    # 1. Temporal Integrity & Contiguity Validation Guard
    years = sorted(f.fiscal_year for f in annual_financials)
    expected_contiguous = list(range(years[0], years[-1] + 1))
    if years != expected_contiguous:
        raise ValueError(
            f"annual_financials must contain contiguous fiscal years with no gaps. "
            f"Supplied: {years}, expected: {expected_contiguous}"
        )
    if balance_sheet.fiscal_year != years[-1]:
        raise ValueError(
            f"balance_sheet.fiscal_year ({balance_sheet.fiscal_year}) must match the latest "
            f"annual_financials fiscal year ({years[-1]})."
        )

    # Chronological sort: T-2, T-1, T_0
    sorted_years = sorted(annual_financials, key=lambda x: x.fiscal_year)

    multi_year_history: List[YearFinancialsResult] = []
    prev_year: Optional[AnnualFinancialInput] = None
    prev_fcf: Optional[float] = None

    for f in sorted_years:
        rev = _validate_finite_number(f.revenue, f"revenue ({f.fiscal_year})")
        gp = _validate_finite_number(f.gross_profit, f"gross_profit ({f.fiscal_year})")
        ebit = _validate_finite_number(f.operating_income, f"operating_income ({f.fiscal_year})")
        ni = _validate_finite_number(f.net_income, f"net_income ({f.fiscal_year})")
        ocf = _validate_finite_number(f.operating_cash_flow, f"operating_cash_flow ({f.fiscal_year})")
        capex = _validate_finite_number(f.capital_expenditures, f"capital_expenditures ({f.fiscal_year})")
        
        fcf = round(ocf - capex, 2)

        # Profitability Margins
        gm_pct = round((gp / rev) * 100.0, 2) if rev != 0 else 0.0
        om_pct = round((ebit / rev) * 100.0, 2) if rev != 0 else 0.0
        nm_pct = round((ni / rev) * 100.0, 2) if rev != 0 else 0.0
        fcf_conv = round((fcf / ni) * 100.0, 2) if ni != 0 else None

        # YoY Growth Rates
        rev_growth = None
        ebit_growth = None
        fcf_growth = None

        if prev_year is not None:
            if prev_year.revenue != 0:
                rev_growth = round(((rev - prev_year.revenue) / abs(prev_year.revenue)) * 100.0, 2)
            if prev_year.operating_income != 0:
                ebit_growth = round(((ebit - prev_year.operating_income) / abs(prev_year.operating_income)) * 100.0, 2)
            if prev_fcf is not None and prev_fcf != 0:
                fcf_growth = round(((fcf - prev_fcf) / abs(prev_fcf)) * 100.0, 2)

        multi_year_history.append(
            YearFinancialsResult(
                fiscal_year=f.fiscal_year,
                revenue=rev,
                gross_profit=gp,
                gross_margin_pct=gm_pct,
                operating_income=ebit,
                operating_margin_pct=om_pct,
                net_income=ni,
                net_margin_pct=nm_pct,
                operating_cash_flow=ocf,
                capital_expenditures=capex,
                free_cash_flow=fcf,
                fcf_conversion_pct=fcf_conv,
                revenue_growth_pct=rev_growth,
                operating_income_growth_pct=ebit_growth,
                fcf_growth_pct=fcf_growth,
            )
        )

        prev_year = f
        prev_fcf = fcf

    # Latest year references
    latest_input = sorted_years[-1]
    latest_res = multi_year_history[-1]

    # Effective Tax Rate Derivation with Provenance Flags
    tax_rate = 0.21
    tax_source = "statutory_default_not_provided"

    if latest_input.pretax_income is not None and latest_input.income_tax_expense is not None:
        pt_income = latest_input.pretax_income
        tax_exp = latest_input.income_tax_expense

        if pt_income <= 0:
            tax_rate = 0.21
            tax_source = "statutory_fallback_due_to_pretax_loss"
        elif tax_exp < 0:
            tax_rate = 0.21
            tax_source = "statutory_fallback_due_to_tax_benefit"
        else:
            tax_rate = round(tax_exp / pt_income, 4)
            tax_source = "derived_from_10k"

    # Liquidity & Solvency Bridge (Consistent definition of Liquid Cash)
    total_liquid = round(balance_sheet.cash_and_equivalents + balance_sheet.marketable_securities, 2)
    total_debt = round(balance_sheet.short_term_debt + balance_sheet.long_term_debt, 2)
    net_debt = round(total_debt - total_liquid, 2)
    net_cash_pos = bool(net_debt < 0)

    # NOPAT & Invested Capital
    nopat = round(latest_res.operating_income * (1.0 - tax_rate), 2)
    invested_capital = round(total_debt + balance_sheet.stockholders_equity - total_liquid, 2)

    # Book Equity Guard: Suppress ROE, ROIC, and Debt/Equity if equity <= 0
    equity = balance_sheet.stockholders_equity
    equity_status = "positive_book_equity"
    roic_pct = None
    roe_pct = None
    total_debt_equity = None

    if equity < 0:
        equity_status = "negative_book_equity_ratios_suppressed"
        logger.warning(
            f"calculate_financial_ratios: Stockholders' equity is negative (${equity:,.1f}M). "
            f"Suppressing ROIC, ROE, and Debt/Equity to prevent distortion."
        )
    elif equity == 0:
        equity_status = "zero_book_equity_ratios_suppressed"
    else:
        # Standard capital return calculation when equity > 0
        if invested_capital > 0:
            roic_pct = round((nopat / invested_capital) * 100.0, 2)
        roe_pct = round((latest_res.net_income / equity) * 100.0, 2)
        total_debt_equity = round(total_debt / equity, 2)

    # EBITDA & Solvency
    ebitda = None
    net_debt_ebitda = None
    ebitda_interp = "ebitda_not_available"

    if latest_input.depreciation_amortization is not None:
        ebitda = round(latest_res.operating_income + latest_input.depreciation_amortization, 2)
        if ebitda > 0:
            net_debt_ebitda = round(net_debt / ebitda, 2)
            ebitda_interp = "net_cash_surplus" if net_cash_pos else "leverage_ratio"
        elif ebitda < 0:
            ebitda_interp = "negative_ebitda"

    # Current Ratio: Explicit is not None checks
    current_ratio = None
    if balance_sheet.current_assets is not None and balance_sheet.current_liabilities is not None:
        if balance_sheet.current_liabilities > 0:
            current_ratio = round(balance_sheet.current_assets / balance_sheet.current_liabilities, 2)

    bs_res = BalanceSheetResult(
        fiscal_year=balance_sheet.fiscal_year,
        cash_and_equivalents=balance_sheet.cash_and_equivalents,
        marketable_securities=balance_sheet.marketable_securities,
        total_liquid_cash=total_liquid,
        short_term_debt=balance_sheet.short_term_debt,
        long_term_debt=balance_sheet.long_term_debt,
        total_debt=total_debt,
        net_debt=net_debt,
        net_cash_position=net_cash_pos,
        stockholders_equity=balance_sheet.stockholders_equity,
        diluted_shares_outstanding=balance_sheet.diluted_shares_outstanding,
        current_assets=balance_sheet.current_assets,
        current_liabilities=balance_sheet.current_liabilities,
    )

    profit_res = ProfitabilityRatiosResult(
        effective_tax_rate_pct=round(tax_rate * 100.0, 2),
        tax_rate_source=tax_source,
        equity_status=equity_status,
        nopat=nopat,
        invested_capital=invested_capital,
        roic_pct=roic_pct,
        roe_pct=roe_pct,
        latest_gross_margin_pct=latest_res.gross_margin_pct,
        latest_operating_margin_pct=latest_res.operating_margin_pct,
        latest_net_margin_pct=latest_res.net_margin_pct,
    )

    solv_res = SolvencyRatiosResult(
        net_debt_to_ebitda=net_debt_ebitda,
        net_debt_to_ebitda_interpretation=ebitda_interp,
        current_ratio=current_ratio,
        total_debt_to_equity=total_debt_equity,
    )

    return {
        "multi_year_history": multi_year_history,
        "balance_sheet": bs_res,
        "profitability_and_return_ratios": profit_res,
        "solvency_and_liquidity_ratios": solv_res,
    }


# ==============================================================================
# 5. Internal Function 2: Sequenced Forensic Red-Flag Detector
# ==============================================================================
def detect_forensic_red_flags(
    annual_inputs: List[AnnualFinancialInput],
    multi_year_history: List[YearFinancialsResult],
    balance_sheet: Optional[BalanceSheetInput] = None,
) -> List[str]:
    """
    Performs algorithmic forensic accounting checks sequenced by data availability:
    - Tier 1a: Net Income vs. Operating Cash Flow divergence.
    - Tier 1b: Chronically weak Free Cash Flow conversion (< 70% across all profitable years).
    - Tier 1c: Chronic OCF deficit (OCF < Net Income in every reported year).
    - Tier 1d: Negative book equity warning.
    - Tier 2 (When AR is present): YoY Accounts Receivable Growth vs. Revenue Growth.
    - Tier 3 (When Inventory is present): YoY Inventory Growth vs. Revenue Growth.
    """
    red_flags: List[str] = []

    # Map inputs by fiscal year for quick lookup
    input_map = {f.fiscal_year: f for f in annual_inputs}

    # --------------------------------------------------------------------------
    # Tier 1a: Net Income vs. OCF Divergence
    # --------------------------------------------------------------------------
    for idx in range(1, len(multi_year_history)):
        cur = multi_year_history[idx]
        prev = multi_year_history[idx - 1]

        ni_change = cur.net_income - prev.net_income
        ocf_change = cur.operating_cash_flow - prev.operating_cash_flow

        ni_growth_pct = (ni_change / abs(prev.net_income)) * 100.0 if prev.net_income != 0 else 0.0
        ocf_growth_pct = (ocf_change / abs(prev.operating_cash_flow)) * 100.0 if prev.operating_cash_flow != 0 else 0.0

        # Divergence: Net Income increased while OCF declined
        if ni_growth_pct > 0.0 and ocf_growth_pct < 0.0:
            red_flags.append(
                f"EARNINGS QUALITY DIVERGENCE (FY{cur.fiscal_year}): Net income increased by "
                f"+{ni_growth_pct:.2f}% (${prev.net_income:,.1f}M -> ${cur.net_income:,.1f}M) while operating "
                f"cash flow declined by {ocf_growth_pct:.2f}% (${prev.operating_cash_flow:,.1f}M -> "
                f"${cur.operating_cash_flow:,.1f}M). This indicates potential accrual expansion, non-operating "
                f"gains, or significant tax/working capital cash timing outflows."
            )

    # --------------------------------------------------------------------------
    # Tier 1b: Chronically Weak FCF Conversion (< 70% across all profitable years)
    # --------------------------------------------------------------------------
    positive_ni_years = [
        h for h in multi_year_history
        if h.net_income > 0 and h.fcf_conversion_pct is not None
    ]
    if len(positive_ni_years) >= 2 and all(h.fcf_conversion_pct < 70.0 for h in positive_ni_years):
        avg_conv = sum(h.fcf_conversion_pct for h in positive_ni_years) / len(positive_ni_years)
        red_flags.append(
            f"WEAK CASH CONVERSION WARNING: Free cash flow conversion (FCF / Net Income) has been chronically "
            f"weak (< 70%) across all reported years with positive earnings (averaging {avg_conv:.1f}%), "
            f"signaling high capital intensity or poor earnings-to-cash realization."
        )

    # --------------------------------------------------------------------------
    # Tier 1c: Chronic OCF Deficit (OCF < Net Income across all years)
    # --------------------------------------------------------------------------
    if len(multi_year_history) >= 2:
        chronic_deficit = all(h.operating_cash_flow < h.net_income for h in multi_year_history)
        if chronic_deficit:
            red_flags.append(
                "CHRONIC ACCRUAL DEFICIT: Operating cash flow was strictly lower than net income in every "
                "reported fiscal year, signaling persistently low cash conversion quality."
            )

    # --------------------------------------------------------------------------
    # Tier 1d: Negative Book Equity Warning
    # --------------------------------------------------------------------------
    if balance_sheet is not None and balance_sheet.stockholders_equity < 0:
        red_flags.append(
            f"NEGATIVE BOOK EQUITY WARNING: Stockholders' equity is negative (${balance_sheet.stockholders_equity:,.1f}M). "
            f"Return on Equity (ROE), Return on Invested Capital (ROIC), and Debt-to-Equity have been suppressed as uninterpretable."
        )

    # --------------------------------------------------------------------------
    # Tier 2: Accounts Receivable vs. Revenue Growth Divergence
    # --------------------------------------------------------------------------
    for idx in range(1, len(multi_year_history)):
        cur_yr = multi_year_history[idx].fiscal_year
        prev_yr = multi_year_history[idx - 1].fiscal_year

        cur_inp = input_map.get(cur_yr)
        prev_inp = input_map.get(prev_yr)

        if cur_inp and prev_inp:
            if cur_inp.accounts_receivable is not None and prev_inp.accounts_receivable is not None:
                prev_ar = prev_inp.accounts_receivable
                cur_ar = cur_inp.accounts_receivable

                if prev_ar > 0:
                    ar_growth_pct = ((cur_ar - prev_ar) / prev_ar) * 100.0
                    rev_growth_pct = multi_year_history[idx].revenue_growth_pct or 0.0
                    spread = ar_growth_pct - rev_growth_pct

                    # If AR grew > 15% faster than revenue
                    if spread > 15.0 and ar_growth_pct > 5.0:
                        red_flags.append(
                            f"RECEIVABLES DIVERGENCE (FY{cur_yr}): Accounts receivable grew by +{ar_growth_pct:.2f}% "
                            f"(${prev_ar:,.1f}M -> ${cur_ar:,.1f}M), significantly outpacing revenue growth of "
                            f"{rev_growth_pct:+.2f}% (spread of {spread:.1f}%). This may signal aggressive "
                            f"revenue recognition, channel stuffing, or customer payment delays."
                        )

    # --------------------------------------------------------------------------
    # Tier 3: Inventory vs. Revenue Growth Divergence
    # --------------------------------------------------------------------------
    for idx in range(1, len(multi_year_history)):
        cur_yr = multi_year_history[idx].fiscal_year
        prev_yr = multi_year_history[idx - 1].fiscal_year

        cur_inp = input_map.get(cur_yr)
        prev_inp = input_map.get(prev_yr)

        if cur_inp and prev_inp:
            if cur_inp.inventories is not None and prev_inp.inventories is not None:
                prev_inv = prev_inp.inventories
                cur_inv = cur_inp.inventories

                # Only run check if the firm actually carries inventory (bypasses software/services)
                if prev_inv > 0 and cur_inv > 0:
                    inv_growth_pct = ((cur_inv - prev_inv) / prev_inv) * 100.0
                    rev_growth_pct = multi_year_history[idx].revenue_growth_pct or 0.0
                    spread = inv_growth_pct - rev_growth_pct

                    # If Inventory grew > 20% faster than revenue
                    if spread > 20.0 and inv_growth_pct > 10.0:
                        red_flags.append(
                            f"INVENTORY ACCUMULATION WARNING (FY{cur_yr}): Inventory increased by +{inv_growth_pct:.2f}% "
                            f"(${prev_inv:,.1f}M -> ${cur_inv:,.1f}M), substantially exceeding revenue growth of "
                            f"{rev_growth_pct:+.2f}% (spread of {spread:.1f}%). This may indicate product "
                            f"obsolescence risk, supply-chain bottlenecks, or slowing end-market sell-through."
                        )

    return red_flags


# ==============================================================================
# 6. Core Sequenced Audit Engine
# ==============================================================================
def audit_financial_metrics(
    annual_financials: List[AnnualFinancialInput],
    balance_sheet: BalanceSheetInput,
) -> Dict[str, Any]:
    """
    Pure Python coordinator executing financial ratio calculations and forensic screening.
    Returns fully validated, structured dictionary conforming to FinancialAuditResult.
    """
    logger.info(
        f"audit_financial_metrics: Auditing {len(annual_financials)} fiscal years for "
        f"FY{balance_sheet.fiscal_year} (Shares: {balance_sheet.diluted_shares_outstanding:,.2f}M)"
    )

    # 1. Deterministic Ratio Calculations (validates contiguous years & temporal matching)
    calc_results = calculate_financial_ratios(
        annual_financials=annual_financials,
        balance_sheet=balance_sheet,
    )

    # 2. Sequenced Forensic Accounting Checks
    forensic_flags = detect_forensic_red_flags(
        annual_inputs=annual_financials,
        multi_year_history=calc_results["multi_year_history"],
        balance_sheet=balance_sheet,
    )

    audit_result = FinancialAuditResult(
        multi_year_history=calc_results["multi_year_history"],
        balance_sheet=calc_results["balance_sheet"],
        profitability_and_return_ratios=calc_results["profitability_and_return_ratios"],
        solvency_and_liquidity_ratios=calc_results["solvency_and_liquidity_ratios"],
        forensic_red_flags=forensic_flags,
    )

    logger.info(
        f"audit_financial_metrics: Completed audit. Net Debt: ${audit_result.balance_sheet.net_debt:,.2f}M "
        f"({'Net Cash' if audit_result.balance_sheet.net_cash_position else 'Net Debt'}) | "
        f"ROIC: {audit_result.profitability_and_return_ratios.roic_pct}% | "
        f"Red flags detected: {len(forensic_flags)}"
    )

    return audit_result.model_dump()


# ==============================================================================
# 7. LangChain Agent Tool Decorator
# ==============================================================================
@tool
def audit_financial_metrics_tool(
    annual_financials: List[AnnualFinancialInput],
    balance_sheet: BalanceSheetInput,
) -> Dict[str, Any]:
    """
    Audit 10-K financial statements and compute deterministic ratios and forensic flags.

    Executes:
    1. Multi-year profitability margins (Gross Margin, Operating Margin, Net Margin).
    2. Free Cash Flow (FCF = Operating Cash Flow - CapEx) and FCF conversion % of Net Income.
    3. Year-over-Year (YoY) growth rates for Revenue, Operating Income, and FCF.
    4. Derived effective tax rate from 10-K pre-tax income and tax provision.
    5. Return on Invested Capital (ROIC) and Return on Equity (ROE).
    6. Solvency and liquidity bridge (Net Debt, Net Debt/EBITDA, Current Ratio).
    7. Sequenced forensic red-flag screener (Net Income vs OCF divergence, weak FCF conversion, AR expansion, Inventory ramp).

    All dollar quantities must be in $ MILLIONS, diluted shares must be in MILLIONS,
    and CapEx must be passed as a positive magnitude.

    Args:
        annual_financials: Chronological list of contiguous annual statement records (typically 3 fiscal years).
                           Each record requires: fiscal_year, revenue, gross_profit, operating_income,
                           net_income, operating_cash_flow, capital_expenditures (positive magnitude).
                           Optional: pretax_income, income_tax_expense, depreciation_amortization,
                           accounts_receivable, inventories.
        balance_sheet: Balance sheet snapshot for the latest fiscal year (must match latest annual_financials year).
                       Requires: fiscal_year, cash_and_equivalents, marketable_securities,
                       short_term_debt, long_term_debt, stockholders_equity, diluted_shares_outstanding.
                       Optional: current_assets, current_liabilities.

    Returns:
        Structured audit report containing multi_year_history, balance_sheet,
        profitability_and_return_ratios, solvency_and_liquidity_ratios, and forensic_red_flags.
    """
    return audit_financial_metrics(
        annual_financials=annual_financials,
        balance_sheet=balance_sheet,
    )
