"""Unit and Integration Tests for Lead Synthesizer Agent (Milestone 6).

Validates:
1. Agent registration in AgentRegistry and prompt template rendering.
2. Full multi-agent synthesis:
   - Ingestion of Moat, Audit, Forecast, DCF Valuation, and Risk payloads.
   - LLM generation of the 3-Pillar Investment Thesis and Executive Summary.
   - Deterministic publication of complete Markdown institutional report.
   - Zero math distortion: verbatim preservation of audited tables and DCF sensitivity matrix.
   - Provenance tracking (synthesis_provenance, year_substituted disclosure).
   - Cross-agent citation deduplication.
3. Graceful handling of partial inputs (e.g. Fast-Path DCF mode without qualitative agents).
4. Exhaustive None-guard resilience: verifying formatting does not crash on None/NaN metrics.
5. BaseAgent.run() interface compatibility.
"""

import unittest
from unittest.mock import MagicMock, patch
from app.agents.registry import AgentRegistry
from app.agents.specialized.prompts import render_prompt
from app.agents.state import (
    BusinessMoatOutput,
    DCFValuationOutput,
    Final10KResearchReport,
    FinancialAuditOutput,
    ForecastOutput,
    ForecastYear,
    RiskAuditOutput,
    RiskDataQuality,
    RiskDisclosureDiff,
    RiskEvidence,
    RiskItem,
    SegmentDetail,
    ThreePillarThesis,
    WACCAudit,
)
from app.agents.tools.risk_disclosure_tools import (
    DisclosurePassage,
    render_risk_evidence_table,
    render_risk_matrix_markdown,
)
from app.agents.tools.financial_math_tools import (
    AnnualFinancialInput,
    BalanceSheetInput,
    audit_financial_metrics,
)
from app.agents.specialized.lead_synthesizer.agent_lead_synthesizer import (
    LeadSynthesizerAgent,
    ResearchSynthesisPayload,
)


def _create_mock_audit() -> FinancialAuditOutput:
    """Helper creating verified FinancialAuditOutput."""
    annual_financials = [
        AnnualFinancialInput(
            fiscal_year=2023,
            revenue=383285.0,
            gross_profit=169148.0,
            operating_income=114301.0,
            pretax_income=113736.0,
            income_tax_expense=16741.0,
            net_income=96995.0,
            operating_cash_flow=110543.0,
            capital_expenditures=10959.0,
        ),
        AnnualFinancialInput(
            fiscal_year=2024,
            revenue=391035.0,
            gross_profit=180683.0,
            operating_income=123216.0,
            pretax_income=123485.0,
            income_tax_expense=29749.0,
            net_income=93736.0,
            operating_cash_flow=118254.0,
            capital_expenditures=9447.0,
        ),
        AnnualFinancialInput(
            fiscal_year=2025,
            revenue=416161.0,
            gross_profit=195201.0,
            operating_income=133050.0,
            pretax_income=132717.0,
            income_tax_expense=20707.0,
            net_income=112010.0,
            operating_cash_flow=111482.0,
            capital_expenditures=12715.0,
            depreciation_amortization=11445.0,
        ),
    ]
    balance_sheet_in = BalanceSheetInput(
        fiscal_year=2025,
        cash_and_equivalents=35934.0,
        marketable_securities=96486.0,
        short_term_debt=10912.0,
        long_term_debt=87745.0,
        stockholders_equity=53736.0,
        weighted_diluted_shares=15004.7,
        current_assets=154388.0,
        current_liabilities=145308.0,
    )
    math_res = audit_financial_metrics(annual_financials, balance_sheet_in)
    math_res["ticker"] = "AAPL"
    math_res["fiscal_year"] = 2025
    math_res["auditor_summary"] = "Audited financial statements for Apple Inc. FY2025."
    math_res["data_quality"] = {"extraction_mode": "deterministic"}
    math_res["income_statement_markdown_table"] = "| Line Item | FY2023 | FY2024 | FY2025 |\n| :--- | :---: | :---: | :---: |\n| Total net sales | $383,285 | $391,035 | $416,161 |"
    math_res["balance_sheet_markdown_table"] = "| Line Item | Sept 2024 | Sept 2025 |\n| :--- | :---: | :---: |\n| Cash & Marketable Securities | $153,004 | $132,420 |"
    math_res["cash_flow_markdown_table"] = "| Line Item | FY2023 | FY2024 | FY2025 |\n| :--- | :---: | :---: |\n| Cash generated by operating activities | $110,543 | $118,254 | $111,482 |"
    math_res["citations"] = [{"chunk_id": "table-chunk-item8-01", "item": "Item 8"}]
    return FinancialAuditOutput.model_validate(math_res)


def _create_mock_moat() -> BusinessMoatOutput:
    """Helper creating verified BusinessMoatOutput."""
    return BusinessMoatOutput(
        ticker="AAPL",
        fiscal_year=2025,
        business_summary="Global technology designer and manufacturer offering consumer devices, software, and services.",
        revenue_architecture="Diversified revenue spanning hardware product sales and high-margin recurring services.",
        primary_product_segments=["iPhone", "Services", "Wearables, Home & Accessories", "Mac", "iPad"],
        segment_details=[
            SegmentDetail(name="iPhone", description="Flagship smartphone product line", growth_drivers=["Apple Intelligence", "Replacement cycles"]),
            SegmentDetail(name="Services", description="Recurring subscriptions, App Store, iCloud, Apple Pay", growth_drivers=["Installed base expansion", "Higher ARPU"]),
        ],
        economic_moat_type="High Switching Costs",
        moat_durability="Wide",
        moat_trajectory="Expanding",
        moat_rationale="Proprietary integrated ecosystem creates immense consumer lock-in and high switching barriers across 2.2B+ active devices.",
        pricing_power_assessment="High premium pricing power evidenced by stable >45% gross margins.",
        customer_concentration="No single customer accounted for 10% or more of net sales in FY25.",
        citations=[{"chunk_id": "narrative-chunk-item1-01", "item": "Item 1"}],
    )


def _create_mock_forecast() -> ForecastOutput:
    """Helper creating verified ForecastOutput."""
    schedule = [
        ForecastYear(projected_year=2026, projected_revenue=441130.7, projected_revenue_growth_pct=6.0, projected_ebit=141161.8, projected_ebit_margin_pct=32.0, projected_nopat=119139.6, projected_capex=13480.0, projected_unlevered_fcf=105659.6),
        ForecastYear(projected_year=2027, projected_revenue=465392.8, projected_revenue_growth_pct=5.5, projected_ebit=149856.5, projected_ebit_margin_pct=32.2, projected_nopat=126478.9, projected_capex=14220.0, projected_unlevered_fcf=112258.9),
        ForecastYear(projected_year=2028, projected_revenue=488662.5, projected_revenue_growth_pct=5.0, projected_ebit=158326.7, projected_ebit_margin_pct=32.4, projected_nopat=133627.7, projected_capex=14930.0, projected_unlevered_fcf=118697.7),
        ForecastYear(projected_year=2029, projected_revenue=510652.3, projected_revenue_growth_pct=4.5, projected_ebit=166472.6, projected_ebit_margin_pct=32.6, projected_nopat=140502.9, projected_capex=15600.0, projected_unlevered_fcf=124902.9),
        ForecastYear(projected_year=2030, projected_revenue=531078.4, projected_revenue_growth_pct=4.0, projected_ebit=174193.7, projected_ebit_margin_pct=32.8, projected_nopat=147019.5, projected_capex=16220.0, projected_unlevered_fcf=130799.5),
    ]
    return ForecastOutput(
        ticker="AAPL",
        fiscal_year=2025,
        base_revenue=416161.0,
        forecast_horizon_years=5,
        revenue_cagr_pct=5.0,
        cumulative_5yr_fcf=592318.6,
        average_annual_fcf=118463.7,
        provenance_mode="simplified_nopat_less_capex",
        guidance_source="md&a_explicit",
        tax_rate_pct=15.6,
        projected_fcfs=[105659.6, 112258.9, 118697.7, 124902.9, 130799.5],
        forecast_schedule=schedule,
        forecast_table_markdown="| Metric | FY26 | FY27 | FY28 | FY29 | FY30 |\n| :--- | :---: | :---: | :---: | :---: |\n| Revenue | $441,131 | $465,393 | $488,663 | $510,652 | $531,078 |",
        growth_rationale="Revenue growth models steady 5% CAGR underpinned by Services expansion and Apple Intelligence upgrade cycle.",
        margin_expansion_rationale="Modest 80bps operating margin expansion over 5 years driven by growing mix of high-margin Services.",
        citations=[{"chunk_id": "narrative-chunk-item7-01", "item": "Item 7"}],
    )


def _create_mock_dcf() -> DCFValuationOutput:
    """Helper creating verified DCFValuationOutput."""
    wacc_audit = WACCAudit(
        wacc=0.0953,
        wacc_pct=9.53,
        cost_of_equity_pct=9.70,
        cost_of_debt_pre_tax_pct=3.85,
        cost_of_debt_after_tax_pct=3.25,
        cost_of_debt_source="derived_from_10k_interest_expense",
        equity_weight_pct=97.2,
        debt_weight_pct=2.8,
        formula_breakdown_markdown="| Component | Weight | Rate | Weighted |\n| :--- | :---: | :---: | :---: |\n| Cost of Equity | 97.2% | 9.70% | 9.43% |\n| After-Tax Debt | 2.8% | 3.25% | 0.09% |\n| **Blended WACC** | **100.0%** | - | **9.53%** |",
    )
    return DCFValuationOutput(
        ticker="AAPL",
        fiscal_year=2025,
        wacc_audit=wacc_audit,
        terminal_growth_rate=0.025,
        discounting_convention="mid_year",
        projected_fcfs=[105659.6, 112258.9, 118697.7, 124902.9, 130799.5],
        pv_explicit_fcfs=460124.0,
        pv_terminal_value=1224850.0,
        terminal_value_pct_of_ev=72.7,
        enterprise_value=1684974.0,
        net_debt=-33775.0,  # Cash surplus
        equity_value=1718749.0,
        diluted_shares=15004.7,
        implied_fair_value_per_share=245.50,
        current_share_price=230.00,
        upside_downside_pct=6.7,
        valuation_stance="Fairly Valued",
        sensitivity_matrix_markdown="| WACC \\ g | 1.9% | 2.2% | 2.5% | 2.8% | 3.1% |\n|:---| :---: | :---: | :---: | :---: | :---: |\n| **8.5%** | $285.20 | $298.10 | $312.50 | $328.60 | $346.80 |\n| **9.5%** | $228.40 | $236.60 | **$245.50** | $255.40 | $266.30 |\n| **10.5%** | $188.70 | $194.20 | $200.10 | $206.50 | $213.50 |",
        valuation_summary="DCF valuation yields $245.50 implied fair value per share based on 9.53% WACC and 2.5% perpetual growth.",
    )


def _create_mock_risk() -> RiskAuditOutput:
    """Helper creating a verified RiskAuditOutput (as emitted after deterministic enforcement)."""
    evidence = RiskEvidence(
        chunk_id="narrative-chunk-item1a-01", quote="The Company is subject to complex and changing laws and regulations worldwide",
        item="Item 1A", breadcrumb="Apple Inc. (AAPL) > 10-K FY2025 > PART I > Item 1A: Risk Factors", verified=True,
    )
    risks = [
        RiskItem(risk_id="R1", risk_category="Regulatory & Legal", risk_title="Antitrust Scrutiny on App Store",
                 risk_summary="Global regulatory enforcement targeting App Store commissions and terms.",
                 likelihood="High", impact="High", severity="Severe", financial_transmission=["Revenue", "Gross Margin"],
                 evidence=[evidence], disclosure_change="Expanded", monitoring_signposts=["App Store fee rulings"]),
        RiskItem(risk_id="R2", risk_category="Supply Chain & Concentration", risk_title="Geographic Supply Chain Concentration",
                 risk_summary="Substantially all manufacturing outsourced to partners in Asia.",
                 likelihood="Medium", impact="High", severity="Severe", financial_transmission=["Gross Margin"],
                 evidence=[evidence], disclosure_change="Unchanged"),
        RiskItem(risk_id="R3", risk_category="Macroeconomic & Geopolitical", risk_title="Foreign Exchange Rate Volatility",
                 risk_summary="Substantial international sales exposed to currency fluctuations.",
                 likelihood="High", impact="Medium", severity="Moderate", financial_transmission=["Revenue"],
                 evidence=[evidence], disclosure_change="Unchanged"),
    ]
    citations = [{"chunk_id": "narrative-chunk-item1a-01", "item": "Item 1A", "breadcrumb": evidence.breadcrumb}]
    return RiskAuditOutput(
        ticker="AAPL",
        fiscal_year=2025,
        identified_risks=risks,
        primary_threat_risk_id="R1",
        primary_existential_threat="Regulatory and antitrust intervention mandating unbundling or alternative payment systems on iOS ecosystem.",
        overall_risk_profile="High",
        disclosure_changes=RiskDisclosureDiff(
            prior_fiscal_year=2024, current_sentences=308, prior_sentences=313, unchanged_sentences=207,
            modified_sentences=42, new_sentences=59, removed_sentences=59, change_ratio_pct=32.8,
            new_passages=[DisclosurePassage(chunk_id="narrative-chunk-item1a-01", text="Beginning in the second quarter of 2025, new tariffs were announced.", similarity=0.04)],
        ),
        data_quality=RiskDataQuality(coverage_mode="full_section", item1a_chunks=47, chars_read=70162, prior_fiscal_year=2024),
        risk_matrix_markdown=render_risk_matrix_markdown(risks),
        evidence_table_markdown=render_risk_evidence_table(citations),
        citations=citations,
    )


def _mock_llm(payload: ResearchSynthesisPayload) -> MagicMock:
    mock_llm = MagicMock()
    mock_structured_llm = MagicMock()
    mock_structured_llm.invoke.return_value = payload
    mock_llm.with_structured_output.return_value = mock_structured_llm
    return mock_llm


class TestAgentLeadSynthesizer(unittest.TestCase):
    """Test suite for Milestone 6: Lead Synthesizer Agent."""

    def setUp(self):
        self.synthesizer = LeadSynthesizerAgent()

    def test_01_initialization_and_registry(self):
        """Verify agent registration and prompt template rendering."""
        agent = AgentRegistry.get("lead_synthesizer")
        self.assertIsInstance(agent, LeadSynthesizerAgent)

        # Verify prompt renders with generic template directives
        prompt = render_prompt("lead_synthesizer", ticker="AAPL", fiscal_year=2025)
        self.assertIn("Managing Director of Global Equity Research", prompt)
        self.assertIn("3-Pillar Investment Thesis", prompt)
        self.assertIn("Final10KResearchReport", prompt)

    def test_02_full_synthesis_end_to_end(self):
        """Verify full synthesis with all 5 agent inputs producing complete Final10KResearchReport."""
        audit = _create_mock_audit()
        moat = _create_mock_moat()
        forecast = _create_mock_forecast()
        dcf = _create_mock_dcf()
        risk = _create_mock_risk()

        mock_payload = ResearchSynthesisPayload(
            full_markdown_report=(
                "# Institutional Equity Research Report: Apple Inc. (AAPL)\n\n"
                "## Executive Valuation Dashboard\n"
                "- Implied Fair Value: **$245.50**\n"
                "- Current Market Price: $230.00\n"
                "- Projected Upside: +6.7%\n\n"
                "## 1. Executive Summary\n"
                "Apple Inc. demonstrates outstanding capital return resilience, vast installed base scale, "
                "and an expanding high-margin Services mix sustaining long-term intrinsic value creation.\n\n"
                "## 2. Institutional 3-Pillar Investment Thesis\n"
                "Institutional synthesis establishes defensibility across business moat, financial durability, and asymmetric valuation upside.\n\n"
                "## 3. Business Operations & Economic Moat Analysis\n"
                "Proprietary integrated ecosystem creates immense consumer lock-in across active devices.\n\n"
                "## 4. Audited Financial Statements & Ratio Performance\n"
                "| Line Item | FY2023 | FY2024 | FY2025 |\n"
                "| :--- | :---: | :---: | :---: |\n"
                "| Total net sales | $383,285 | $391,035 | $416,161 |\n\n"
                "## 5. 5-Year Financial Forecast & Cash Flow Schedule\n"
                "Forecast models steady 5% CAGR underpinned by Services expansion and Apple Intelligence upgrade cycle.\n\n"
                "## 6. Discounted Cash Flow (DCF) Valuation & Sensitivity\n"
                "| Component | Weight | Rate | Weighted |\n"
                "| :--- | :---: | :---: | :---: |\n"
                "| **Blended WACC** | **100.0%** | - | **9.53%** |\n\n"
                "DCF sensitivity benchmark yields implied fair value of **$245.50**.\n\n"
                "## 7. Material Risk Factors & Existential Overhangs\n"
                "Primary risks center around antitrust regulatory probes into App Store commissions and Asian supply chain concentration.\n\n"
                "## 8. Regulatory Disclaimers & Audit Breadcrumbs\n"
                "This report is for institutional research purposes only and incorporates audited SEC filings."
            ),
            executive_summary=(
                "Apple Inc. demonstrates outstanding capital return resilience, vast installed base scale, "
                "and an expanding high-margin Services mix sustaining long-term intrinsic value creation."
            ),
            valuation_stance="Fairly Valued",
            pillar_1_business_moat=(
                "Proprietary integrated hardware-software ecosystem creates insurmountable consumer lock-in and high switching costs across 2.2B+ devices."
            ),
            pillar_2_financial_durability=(
                "Pristine balance sheet structure, world-class ROIC, and disciplined capital allocation driving over $100B in annual operating cash flow."
            ),
            pillar_3_valuation_asymmetry=(
                "DCF valuation yields $245.50 fair value, establishing favorable risk-reward asymmetry and downside margin of safety."
            ),
        )

        mock_llm = MagicMock()
        mock_structured_llm = MagicMock()
        mock_structured_llm.invoke.return_value = mock_payload
        mock_llm.with_structured_output.return_value = mock_structured_llm

        with patch.object(self.synthesizer, "_get_llm", return_value=mock_llm):
            report = self.synthesizer.synthesize(
                ticker="AAPL",
                company_name="Apple Inc.",
                fiscal_year=2025,
                business_moat=moat,
                financial_audit=audit,
                forecast=forecast,
                dcf_valuation=dcf,
                risk_audit=risk,
                year_substituted=False,
            )

        self.assertIsInstance(report, Final10KResearchReport)
        self.assertEqual(report.ticker, "AAPL")
        self.assertEqual(report.company_name, "Apple Inc.")
        self.assertEqual(report.fiscal_year, 2025)
        self.assertEqual(report.year_substituted, False)

        # Provenance must be tagged
        self.assertIn(report.synthesis_provenance, ["llm_structured", "llm_json_fallback", "template_default"])

        # Valuation numbers must match DCF output exactly (Zero Hallucination)
        self.assertAlmostEqual(report.implied_fair_value_per_share, 245.50, places=2)
        self.assertEqual(report.current_share_price, 230.00)
        self.assertEqual(report.upside_downside_pct, 6.7)
        self.assertEqual(report.valuation_stance, "Fairly Valued")

        # Verify 3-Pillar Thesis components
        thesis = report.three_pillar_thesis
        self.assertIsInstance(thesis, ThreePillarThesis)
        self.assertTrue(len(thesis.pillar_1_business_moat) > 20)
        self.assertTrue(len(thesis.pillar_2_financial_durability) > 20)
        self.assertTrue(len(thesis.pillar_3_valuation_asymmetry) > 20)

        # Verify Executive Summary
        self.assertTrue(len(report.executive_summary) > 50)

        # Verify publication Markdown report sections
        md = report.full_markdown_report
        self.assertIn("# Institutional Equity Research Report: Apple Inc. (AAPL)", md)
        self.assertIn("## Executive Valuation Dashboard", md)
        self.assertIn("$245.50", md)
        self.assertIn("## 1. Executive Summary", md)
        self.assertIn("## 2. Institutional 3-Pillar Investment Thesis", md)
        self.assertIn("## 3. Business Operations & Economic Moat Analysis", md)
        self.assertIn("## 4. Audited Financial Statements & Ratio Performance", md)
        self.assertIn("## 5. 5-Year Financial Forecast & Cash Flow Schedule", md)
        self.assertIn("## 6. Discounted Cash Flow (DCF) Valuation & Sensitivity", md)
        self.assertIn("## 7. Material Risk Factors & Existential Overhangs", md)
        self.assertIn("## 8. Regulatory Disclaimers & Audit Breadcrumbs", md)
        self.assertIn("Synthesis Provenance:", md)

        # Verify raw tables preserved verbatim
        self.assertIn("| Total net sales | $383,285 | $391,035 | $416,161 |", md)
        self.assertIn("| **Blended WACC** | **100.0%** | - | **9.53%** |", md)
        self.assertIn("**$245.50**", md)

        # Verify citation consolidation & deduplication
        self.assertEqual(len(report.all_citations), 4)
        chunk_ids = [c["chunk_id"] for c in report.all_citations]
        self.assertIn("table-chunk-item8-01", chunk_ids)
        self.assertIn("narrative-chunk-item1-01", chunk_ids)
        self.assertIn("narrative-chunk-item7-01", chunk_ids)
        self.assertIn("narrative-chunk-item1a-01", chunk_ids)

    def test_03_partial_synthesis_with_year_substitution(self):
        """Verify synthesis in Fast-Path DCF mode with year substitution flag."""
        audit = _create_mock_audit()
        forecast = _create_mock_forecast()
        dcf = _create_mock_dcf()

        mock_partial_payload = ResearchSynthesisPayload(
            full_markdown_report=(
                "# Institutional Equity Research Report: Apple Inc. (AAPL)\n\n"
                "## Executive Valuation Dashboard\n"
                "- Implied Fair Value: **$245.50**\n\n"
                "## 4. Audited Financial Statements & Ratio Performance\n"
                "| Line Item | FY2023 | FY2024 | FY2025 |\n"
                "| :--- | :---: | :---: | :---: |\n"
                "| Total net sales | $383,285 | $391,035 | $416,161 |\n\n"
                "## 6. Discounted Cash Flow (DCF) Valuation & Sensitivity\n"
                "DCF valuation yields $245.50 fair value."
            ),
            executive_summary="Fast-path DCF valuation report for Apple Inc. evaluating audited financial trends.",
            valuation_stance="Fairly Valued",
            pillar_1_business_moat=None,
            pillar_2_financial_durability="Strong balance sheet with robust cash reserves and positive free cash flows.",
            pillar_3_valuation_asymmetry="Intrinsic DCF fair value provides valuation perspective against market price.",
        )

        mock_llm = MagicMock()
        mock_structured_llm = MagicMock()
        mock_structured_llm.invoke.return_value = mock_partial_payload
        mock_llm.with_structured_output.return_value = mock_structured_llm

        with patch.object(self.synthesizer, "_get_llm", return_value=mock_llm):
            report = self.synthesizer.synthesize(
                ticker="AAPL",
                company_name="Apple Inc.",
                fiscal_year=2025,
                financial_audit=audit,
                forecast=forecast,
                dcf_valuation=dcf,
                year_substituted=True,
            )

        self.assertIsInstance(report, Final10KResearchReport)
        self.assertEqual(report.implied_fair_value_per_share, 245.50)
        self.assertEqual(report.year_substituted, True)
        self.assertIn("Filing Provenance Note", report.full_markdown_report)
        self.assertIn("## Executive Valuation Dashboard", report.full_markdown_report)
        self.assertIn("## 4. Audited Financial Statements & Ratio Performance", report.full_markdown_report)
        self.assertIn("## 6. Discounted Cash Flow (DCF) Valuation & Sensitivity", report.full_markdown_report)

    def test_04_exhaustive_none_guard_resilience(self):
        """Verify _fmt helper gracefully handles None, NaN, and Inf without TypeError exceptions."""
        fmt = LeadSynthesizerAgent._fmt
        self.assertEqual(fmt(None, ".1f"), "N/A")
        self.assertEqual(fmt(float("nan"), ".1f"), "N/A")
        self.assertEqual(fmt(float("inf"), ".1f"), "N/A")
        self.assertEqual(fmt(12.345, ".1f", suffix="%"), "12.3%")
        self.assertEqual(fmt(1234.56, ",.1f", prefix="$", suffix="M"), "$1,234.6M")

    def test_06_risk_factors_prompt_embeds_verified_context(self):
        """Verify the risk-only route renders the section template and the verified risk artifacts."""
        risk = _create_mock_risk()
        prompt = render_prompt(
            "lead_synthesizer", ticker="AAPL", company_name="Apple Inc.", fiscal_year=2025,
            risk_audit=risk, query_type="risk_factors_only", user_query="What are Apple's key risks?",
        )
        self.assertIn("VERIFIED RISK MATRIX (embed verbatim):", prompt)
        self.assertIn(risk.risk_matrix_markdown, prompt)
        self.assertIn(risk.evidence_table_markdown, prompt)
        self.assertIn("# Material Risk Factors & Existential Overhangs: Apple Inc. (AAPL)", prompt)
        self.assertIn("**Overall Risk Profile**: **High** | **Severe Risks**: 2 of 3 | **Disclosure Baseline**: vs FY2024", prompt)
        self.assertIn("## 4. Primary Existential Threat & Bear-Case Linkage", prompt)
        self.assertIn("Primary Existential Threat: R1", prompt)
        self.assertIn('Evidence [narrative-chunk-item1a-01 | Item 1A]: "The Company is subject to complex', prompt)
        self.assertIn("YEAR-OVER-YEAR DISCLOSURE CHANGES (FY2025 vs FY2024)", prompt)
        self.assertIn("Do NOT state an analysis date", prompt)

        instruction = render_prompt(
            "prompt_synthesizer_instruction.j2", ticker="AAPL", company_name="Apple Inc.", fiscal_year=2025,
            query_type="risk_factors_only",
        )
        self.assertIn("6 sections", instruction)
        self.assertIn("VERIFIED RISK MATRIX", instruction)

    def test_07_risk_report_guards_insert_matrix_and_strip_dates(self):
        """Verify the deterministic guards: matrix inserted when missing, invented dates removed."""
        risk = _create_mock_risk()
        payload = ResearchSynthesisPayload(
            full_markdown_report=(
                "# Material Risk Factors & Existential Overhangs: Apple Inc. (AAPL)\n\n"
                "> **Filing Source**: SEC Form 10-K (FY2025) | **Analysis Date**: October 2023 | **Overall Risk Profile**: **High**\n"
                "> **Report Date**: October 2023\n\n"
                "## 1. Risk Summary\n- Antitrust intervention is the primary threat.\n\n"
                "## 2. Verified Risk Matrix\nThe matrix ranks severity as likelihood x impact.\n\n"
                "## 3. Risk-by-Risk Assessment\n### R1 — Antitrust Scrutiny on App Store\nDetail."
            ),
            executive_summary="Antitrust intervention is Apple's primary existential threat; overall risk profile is High.",
        )
        with patch.object(self.synthesizer, "_get_llm", return_value=_mock_llm(payload)):
            report = self.synthesizer.synthesize(
                ticker="AAPL", company_name="Apple Inc.", fiscal_year=2025, risk_audit=risk,
                query_type="risk_factors_only",
            )
        md = report.full_markdown_report
        self.assertNotIn("Analysis Date", md)
        self.assertNotIn("Report Date", md)
        self.assertNotIn("October 2023", md)
        self.assertIn("> **Filing Source**: SEC Form 10-K (FY2025) | **Overall Risk Profile**: **High**", md)
        self.assertIn(risk.risk_matrix_markdown, md)
        self.assertLess(md.index("## 2. Verified Risk Matrix"), md.index("| R1 | Antitrust Scrutiny on App Store"))
        self.assertLess(md.index("| R1 | Antitrust Scrutiny on App Store"), md.index("## 3. Risk-by-Risk Assessment"))
        self.assertEqual(md.count("| R1 | Antitrust Scrutiny on App Store"), 1)

    def test_08_risk_matrix_not_duplicated_or_forced_on_other_routes(self):
        """Verify an embedded matrix is left alone and non-risk routes are untouched."""
        risk = _create_mock_risk()
        embedded = (
            "# Material Risk Factors & Existential Overhangs: Apple Inc. (AAPL)\n\n## 2. Verified Risk Matrix\n"
            + risk.risk_matrix_markdown.replace(" | ", "  |  ")
        )
        payload = ResearchSynthesisPayload(full_markdown_report=embedded, executive_summary="Risk summary for Apple Inc. FY2025.")
        with patch.object(self.synthesizer, "_get_llm", return_value=_mock_llm(payload)):
            report = self.synthesizer.synthesize(
                ticker="AAPL", company_name="Apple Inc.", fiscal_year=2025, risk_audit=risk, query_type="risk_factors_only",
            )
        self.assertEqual(report.full_markdown_report.count("Antitrust Scrutiny on App Store"), 1)

        moat_payload = ResearchSynthesisPayload(full_markdown_report="# Moat\nBody", executive_summary="Moat summary for Apple Inc.")
        with patch.object(self.synthesizer, "_get_llm", return_value=_mock_llm(moat_payload)):
            report = self.synthesizer.synthesize(
                ticker="AAPL", company_name="Apple Inc.", fiscal_year=2025, risk_audit=risk, query_type="business_moat_only",
            )
        self.assertNotIn("Verified Risk Matrix", report.full_markdown_report)

    def test_09_yoy_claims_stripped_without_baseline(self):
        """Verify year-over-year claims are removed from risk sections when no prior-year baseline exists."""
        risk = _create_mock_risk().model_copy(update={"disclosure_changes": None})
        prompt = render_prompt(
            "lead_synthesizer", ticker="AAPL", company_name="Apple Inc.", fiscal_year=2025,
            risk_audit=risk, query_type="risk_factors_only",
        )
        self.assertIn("NO PRIOR-YEAR BASELINE", prompt)
        self.assertIn("NO BASELINE EXISTS", prompt)

        payload = ResearchSynthesisPayload(
            full_markdown_report=(
                "# Material Risk Factors & Existential Overhangs: Apple Inc. (AAPL)\n"
                "> **Filing Source**: SEC Form 10-K (FY2025) | **Disclosure Baseline**: not assessed\n\n"
                "## 1. Risk Summary\n"
                "- Antitrust intervention is the primary existential threat.\n"
                "- Overall, the risk profile is High with two Severe risks.\n"
                "- A significant year-over-year change includes the heightened focus on cybersecurity threats.\n\n"
                "## 2. Verified Risk Matrix\n" + risk.risk_matrix_markdown + "\n\n"
                "## 3. Risk-by-Risk Assessment\n"
                "Supply concentration is unchanged in structure. Compared to the prior year, the language is broader.\n\n"
                "## 5. Year-over-Year Disclosure Changes\n"
                "The year-over-year change was not assessed as there is no prior-year baseline.\n"
            ),
            executive_summary="Antitrust is the primary threat. The year-over-year disclosures expanded on tariffs.",
        )
        with patch.object(self.synthesizer, "_get_llm", return_value=_mock_llm(payload)):
            report = self.synthesizer.synthesize(
                ticker="AAPL", company_name="Apple Inc.", fiscal_year=2025, risk_audit=risk, query_type="risk_factors_only",
            )
        md = report.full_markdown_report
        self.assertNotIn("heightened focus on cybersecurity", md)
        self.assertNotIn("Compared to the prior year", md)
        self.assertIn("Supply concentration is unchanged in structure.", md)
        self.assertIn("- Overall, the risk profile is High with two Severe risks.", md)
        self.assertIn("The year-over-year change was not assessed as there is no prior-year baseline.", md)
        self.assertIn("vs prior year |", md)  # matrix header untouched
        self.assertEqual(report.executive_summary, "Antitrust is the primary threat.")

        with_baseline = _create_mock_risk()
        with patch.object(self.synthesizer, "_get_llm", return_value=_mock_llm(payload)):
            report = self.synthesizer.synthesize(
                ticker="AAPL", company_name="Apple Inc.", fiscal_year=2025, risk_audit=with_baseline, query_type="risk_factors_only",
            )
        self.assertIn("heightened focus on cybersecurity", report.full_markdown_report)

    def test_10_risk_audit_trail_rendered_in_code(self):
        """Verify data-quality notes and uncited quantified disclosures reach section 6 even if the model omits them."""
        base = _create_mock_risk()
        risk = base.model_copy(update={"data_quality": base.data_quality.model_copy(update={
            "notes": ["1 of 3 quantified Item 1A disclosures are not cited by any verified risk."],
            "quantified_uncovered": ["Sales to one direct customer represented 22% of total revenue."],
        })})
        payload = ResearchSynthesisPayload(
            full_markdown_report=(
                "# Material Risk Factors & Existential Overhangs: Apple Inc. (AAPL)\n\n"
                "## 2. Verified Risk Matrix\n" + risk.risk_matrix_markdown + "\n\n"
                "## 6. Filing Evidence & Audit Trail\n" + risk.evidence_table_markdown + "\n\n"
                "> *Synthesis Provenance: `llm_structured`*"
            ),
            executive_summary="Antitrust intervention is the primary threat for Apple Inc.",
        )
        with patch.object(self.synthesizer, "_get_llm", return_value=_mock_llm(payload)):
            report = self.synthesizer.synthesize(
                ticker="AAPL", company_name="Apple Inc.", fiscal_year=2025, risk_audit=risk, query_type="risk_factors_only",
            )
        md = report.full_markdown_report
        self.assertIn("**Risk analysis data-quality notes**\n- 1 of 3 quantified Item 1A disclosures", md)
        self.assertIn('- "Sales to one direct customer represented 22% of total revenue."', md)
        self.assertLess(md.index("## 6. Filing Evidence & Audit Trail"), md.index("**Risk analysis data-quality notes**"))
        self.assertLess(md.index("**Quantified Item 1A disclosures"), md.index("> *Synthesis Provenance"))
        self.assertEqual(md.count("Synthesis Provenance"), 1)

        # Already rendered by the model -> not duplicated.
        self.assertEqual(LeadSynthesizerAgent._ensure_risk_audit_trail(md, risk), md)

    def test_05_run_agent_output_interface(self):
        """Verify BaseAgent.run() interface compatibility for LeadSynthesizer."""
        output = self.synthesizer.run([
            {"role": "user", "content": "Generate final report for Apple"}
        ])
        self.assertIn("LeadSynthesizerAgent", output.content)


if __name__ == "__main__":
    unittest.main()
