"""Unit and Integration Tests for Lead Synthesizer Agent (Milestone 6).

Validates:
1. Agent registration in AgentRegistry and prompt template rendering.
2. Full multi-agent synthesis:
   - Ingestion of Moat, Audit, Forecast, DCF Valuation, and Risk payloads.
   - LLM generation of the 3-Pillar Investment Thesis and Executive Summary.
   - Deterministic publication of complete Markdown institutional report.
   - Zero math distortion: verbatim preservation of audited tables and DCF sensitivity matrix.
   - Provenance tracking (synthesis_provenance, year_substituted disclosure).
   - Cross-agent citation deduplication.
3. Graceful handling of partial inputs (e.g. Fast-Path DCF mode without qualitative agents).
4. Exhaustive None-guard resilience: verifying formatting does not crash on None/NaN metrics.
5. BaseAgent.run() interface compatibility.
"""

import unittest
from app.agents.registry import AgentRegistry
from app.agents.specialized.prompts import render_prompt
from app.agents.state import (
    BusinessMoatOutput,
    DCFValuationOutput,
    Final10KResearchReport,
    FinancialAuditOutput,
    ForecastOutput,
    ForecastYear,
    RiskAuditOutput,
    RiskItem,
    SegmentDetail,
    ThreePillarThesis,
    WACCAudit,
)
from app.agents.tools.financial_math_tools import (
    AnnualFinancialInput,
    BalanceSheetInput,
    audit_financial_metrics,
)
from app.agents.specialized.lead_synthesizer import LeadSynthesizerAgent


def _create_mock_audit() -> FinancialAuditOutput:
    """Helper creating verified FinancialAuditOutput."""
    annual_financials = [
        AnnualFinancialInput(
            fiscal_year=2023,
            revenue=383285.0,
            gross_profit=169148.0,
            operating_income=114301.0,
            pretax_income=113736.0,
            income_tax_expense=16741.0,
            net_income=96995.0,
            operating_cash_flow=110543.0,
            capital_expenditures=10959.0,
        ),
        AnnualFinancialInput(
            fiscal_year=2024,
            revenue=391035.0,
            gross_profit=180683.0,
            operating_income=123216.0,
            pretax_income=123485.0,
            income_tax_expense=29749.0,
            net_income=93736.0,
            operating_cash_flow=118254.0,
            capital_expenditures=9447.0,
        ),
        AnnualFinancialInput(
            fiscal_year=2025,
            revenue=416161.0,
            gross_profit=195201.0,
            operating_income=133050.0,
            pretax_income=132717.0,
            income_tax_expense=20707.0,
            net_income=112010.0,
            operating_cash_flow=111482.0,
            capital_expenditures=12715.0,
            depreciation_amortization=11445.0,
        ),
    ]
    balance_sheet_in = BalanceSheetInput(
        fiscal_year=2025,
        cash_and_equivalents=35934.0,
        marketable_securities=96486.0,
        short_term_debt=10912.0,
        long_term_debt=87745.0,
        stockholders_equity=53736.0,
        diluted_shares_outstanding=15004.7,
        current_assets=154388.0,
        current_liabilities=145308.0,
    )
    math_res = audit_financial_metrics(annual_financials, balance_sheet_in)
    math_res["ticker"] = "AAPL"
    math_res["fiscal_year"] = 2025
    math_res["auditor_summary"] = "Audited financial statements for Apple Inc. FY2025."
    math_res["income_statement_markdown_table"] = "| Line Item | FY2023 | FY2024 | FY2025 |\n| :--- | :---: | :---: | :---: |\n| Total net sales | $383,285 | $391,035 | $416,161 |"
    math_res["balance_sheet_markdown_table"] = "| Line Item | Sept 2024 | Sept 2025 |\n| :--- | :---: | :---: |\n| Cash & Marketable Securities | $153,004 | $132,420 |"
    math_res["cash_flow_markdown_table"] = "| Line Item | FY2023 | FY2024 | FY2025 |\n| :--- | :---: | :---: |\n| Cash generated by operating activities | $110,543 | $118,254 | $111,482 |"
    math_res["citations"] = [{"chunk_id": "table-chunk-item8-01", "item": "Item 8"}]
    return FinancialAuditOutput.model_validate(math_res)


def _create_mock_moat() -> BusinessMoatOutput:
    """Helper creating verified BusinessMoatOutput."""
    return BusinessMoatOutput(
        ticker="AAPL",
        fiscal_year=2025,
        business_summary="Global technology designer and manufacturer offering consumer devices, software, and services.",
        revenue_architecture="Diversified revenue spanning hardware product sales and high-margin recurring services.",
        primary_product_segments=["iPhone", "Services", "Wearables, Home & Accessories", "Mac", "iPad"],
        segment_details=[
            SegmentDetail(name="iPhone", description="Flagship smartphone product line", growth_drivers=["Apple Intelligence", "Replacement cycles"]),
            SegmentDetail(name="Services", description="Recurring subscriptions, App Store, iCloud, Apple Pay", growth_drivers=["Installed base expansion", "Higher ARPU"]),
        ],
        economic_moat_type="High Switching Costs",
        moat_durability="Wide",
        moat_trajectory="Expanding",
        moat_rationale="Proprietary integrated ecosystem creates immense consumer lock-in and high switching barriers across 2.2B+ active devices.",
        pricing_power_assessment="High premium pricing power evidenced by stable >45% gross margins.",
        customer_concentration="No single customer accounted for 10% or more of net sales in FY25.",
        citations=[{"chunk_id": "narrative-chunk-item1-01", "item": "Item 1"}],
    )


def _create_mock_forecast() -> ForecastOutput:
    """Helper creating verified ForecastOutput."""
    schedule = [
        ForecastYear(projected_year=2026, projected_revenue=441130.7, projected_revenue_growth_pct=6.0, projected_ebit=141161.8, projected_ebit_margin_pct=32.0, projected_nopat=119139.6, projected_capex=13480.0, projected_unlevered_fcf=105659.6),
        ForecastYear(projected_year=2027, projected_revenue=465392.8, projected_revenue_growth_pct=5.5, projected_ebit=149856.5, projected_ebit_margin_pct=32.2, projected_nopat=126478.9, projected_capex=14220.0, projected_unlevered_fcf=112258.9),
        ForecastYear(projected_year=2028, projected_revenue=488662.5, projected_revenue_growth_pct=5.0, projected_ebit=158326.7, projected_ebit_margin_pct=32.4, projected_nopat=133627.7, projected_capex=14930.0, projected_unlevered_fcf=118697.7),
        ForecastYear(projected_year=2029, projected_revenue=510652.3, projected_revenue_growth_pct=4.5, projected_ebit=166472.6, projected_ebit_margin_pct=32.6, projected_nopat=140502.9, projected_capex=15600.0, projected_unlevered_fcf=124902.9),
        ForecastYear(projected_year=2030, projected_revenue=531078.4, projected_revenue_growth_pct=4.0, projected_ebit=174193.7, projected_ebit_margin_pct=32.8, projected_nopat=147019.5, projected_capex=16220.0, projected_unlevered_fcf=130799.5),
    ]
    return ForecastOutput(
        ticker="AAPL",
        fiscal_year=2025,
        base_revenue=416161.0,
        forecast_horizon_years=5,
        revenue_cagr_pct=5.0,
        cumulative_5yr_fcf=592318.6,
        average_annual_fcf=118463.7,
        provenance_mode="simplified_nopat_less_capex",
        guidance_source="md&a_explicit",
        tax_rate_pct=15.6,
        projected_fcfs=[105659.6, 112258.9, 118697.7, 124902.9, 130799.5],
        forecast_schedule=schedule,
        forecast_table_markdown="| Metric | FY26 | FY27 | FY28 | FY29 | FY30 |\n| :--- | :---: | :---: | :---: | :---: |\n| Revenue | $441,131 | $465,393 | $488,663 | $510,652 | $531,078 |",
        growth_rationale="Revenue growth models steady 5% CAGR underpinned by Services expansion and Apple Intelligence upgrade cycle.",
        margin_expansion_rationale="Modest 80bps operating margin expansion over 5 years driven by growing mix of high-margin Services.",
        citations=[{"chunk_id": "narrative-chunk-item7-01", "item": "Item 7"}],
    )


def _create_mock_dcf() -> DCFValuationOutput:
    """Helper creating verified DCFValuationOutput."""
    wacc_audit = WACCAudit(
        wacc=0.0953,
        wacc_pct=9.53,
        cost_of_equity_pct=9.70,
        cost_of_debt_pre_tax_pct=3.85,
        cost_of_debt_after_tax_pct=3.25,
        cost_of_debt_source="derived_from_10k_interest_expense",
        equity_weight_pct=97.2,
        debt_weight_pct=2.8,
        formula_breakdown_markdown="| Component | Weight | Rate | Weighted |\n| :--- | :---: | :---: | :---: |\n| Cost of Equity | 97.2% | 9.70% | 9.43% |\n| After-Tax Debt | 2.8% | 3.25% | 0.09% |\n| **Blended WACC** | **100.0%** | - | **9.53%** |",
    )
    return DCFValuationOutput(
        ticker="AAPL",
        fiscal_year=2025,
        wacc_audit=wacc_audit,
        terminal_growth_rate=0.025,
        discounting_convention="mid_year",
        projected_fcfs=[105659.6, 112258.9, 118697.7, 124902.9, 130799.5],
        pv_explicit_fcfs=460124.0,
        pv_terminal_value=1224850.0,
        terminal_value_pct_of_ev=72.7,
        enterprise_value=1684974.0,
        net_debt=-33775.0,  # Cash surplus
        equity_value=1718749.0,
        diluted_shares=15004.7,
        implied_fair_value_per_share=245.50,
        current_share_price=230.00,
        upside_downside_pct=6.7,
        valuation_stance="Fairly Valued",
        sensitivity_matrix_markdown="| WACC \\ g | 1.9% | 2.2% | 2.5% | 2.8% | 3.1% |\n|:---| :---: | :---: | :---: | :---: | :---: |\n| **8.5%** | $285.20 | $298.10 | $312.50 | $328.60 | $346.80 |\n| **9.5%** | $228.40 | $236.60 | **$245.50** | $255.40 | $266.30 |\n| **10.5%** | $188.70 | $194.20 | $200.10 | $206.50 | $213.50 |",
        valuation_summary="DCF valuation yields $245.50 implied fair value per share based on 9.53% WACC and 2.5% perpetual growth.",
    )


def _create_mock_risk() -> RiskAuditOutput:
    """Helper creating verified RiskAuditOutput."""
    return RiskAuditOutput(
        ticker="AAPL",
        fiscal_year=2025,
        identified_risks=[
            RiskItem(risk_category="Regulatory & Legal", risk_title="Antitrust Scrutiny on App Store", risk_summary="Global regulatory enforcement (e.g. EU Digital Markets Act, US DOJ antitrust lawsuit) targeting App Store commissions and terms.", severity="Severe"),
            RiskItem(risk_category="Supply Chain & Concentration", risk_title="Geographic Supply Chain Concentration", risk_summary="Substantially all manufacturing and assembly operations outsourced to partners in Asia, primarily China and Taiwan.", severity="Severe"),
            RiskItem(risk_category="Macroeconomic & Geopolitical", risk_title="Foreign Exchange Rate Volatility", risk_summary="Substantial international sales exposed to currency fluctuations relative to the US dollar.", severity="Moderate"),
        ],
        primary_existential_threat="Regulatory and antitrust intervention mandating unbundling or alternative payment systems on iOS ecosystem.",
        overall_risk_profile="Moderate",
        citations=[{"chunk_id": "narrative-chunk-item1a-01", "item": "Item 1A"}],
    )


class TestAgentLeadSynthesizer(unittest.TestCase):
    """Test suite for Milestone 6: Lead Synthesizer Agent."""

    def setUp(self):
        self.synthesizer = LeadSynthesizerAgent()

    def test_01_initialization_and_registry(self):
        """Verify agent registration and prompt template rendering."""
        agent = AgentRegistry.get("lead_synthesizer")
        self.assertIsInstance(agent, LeadSynthesizerAgent)

        # Verify prompt renders with generic template directives
        prompt = render_prompt("lead_synthesizer", ticker="AAPL", fiscal_year=2025)
        self.assertIn("Managing Director of Global Equity Research", prompt)
        self.assertIn("3-Pillar Investment Thesis", prompt)
        self.assertIn("Final10KResearchReport", prompt)

    def test_02_full_synthesis_end_to_end(self):
        """Verify full synthesis with all 5 agent inputs producing complete Final10KResearchReport."""
        audit = _create_mock_audit()
        moat = _create_mock_moat()
        forecast = _create_mock_forecast()
        dcf = _create_mock_dcf()
        risk = _create_mock_risk()

        report = self.synthesizer.synthesize(
            ticker="AAPL",
            company_name="Apple Inc.",
            fiscal_year=2025,
            business_moat=moat,
            financial_audit=audit,
            forecast=forecast,
            dcf_valuation=dcf,
            risk_audit=risk,
            year_substituted=False,
        )

        self.assertIsInstance(report, Final10KResearchReport)
        self.assertEqual(report.ticker, "AAPL")
        self.assertEqual(report.company_name, "Apple Inc.")
        self.assertEqual(report.fiscal_year, 2025)
        self.assertEqual(report.year_substituted, False)

        # Provenance must be tagged
        self.assertIn(report.synthesis_provenance, ["llm_structured", "llm_json_fallback", "template_default"])

        # Valuation numbers must match DCF output exactly (Zero Hallucination)
        self.assertAlmostEqual(report.implied_fair_value_per_share, 245.50, places=2)
        self.assertEqual(report.current_share_price, 230.00)
        self.assertEqual(report.upside_downside_pct, 6.7)
        self.assertEqual(report.valuation_stance, "Fairly Valued")

        # Verify 3-Pillar Thesis components
        thesis = report.three_pillar_thesis
        self.assertIsInstance(thesis, ThreePillarThesis)
        self.assertTrue(len(thesis.pillar_1_business_moat) > 20)
        self.assertTrue(len(thesis.pillar_2_financial_durability) > 20)
        self.assertTrue(len(thesis.pillar_3_valuation_asymmetry) > 20)

        # Verify Executive Summary
        self.assertTrue(len(report.executive_summary) > 50)

        # Verify publication Markdown report sections
        md = report.full_markdown_report
        self.assertIn("# Institutional Equity Research Report: Apple Inc. (AAPL)", md)
        self.assertIn("## Executive Valuation Dashboard", md)
        self.assertIn("$245.50", md)
        self.assertIn("## 1. Executive Summary", md)
        self.assertIn("## 2. Institutional 3-Pillar Investment Thesis", md)
        self.assertIn("## 3. Business Operations & Economic Moat Analysis", md)
        self.assertIn("## 4. Audited Financial Statements & Ratio Performance", md)
        self.assertIn("## 5. 5-Year Financial Forecast & Cash Flow Schedule", md)
        self.assertIn("## 6. Discounted Cash Flow (DCF) Valuation & Sensitivity", md)
        self.assertIn("## 7. Material Risk Factors & Existential Overhangs", md)
        self.assertIn("## 8. Regulatory Disclaimers & Audit Breadcrumbs", md)
        self.assertIn("Synthesis Provenance:", md)

        # Verify raw tables preserved verbatim
        self.assertIn("| Total net sales | $383,285 | $391,035 | $416,161 |", md)
        self.assertIn("| **Blended WACC** | **100.0%** | - | **9.53%** |", md)
        self.assertIn("**$245.50**", md)

        # Verify citation consolidation & deduplication
        self.assertEqual(len(report.all_citations), 4)
        chunk_ids = [c["chunk_id"] for c in report.all_citations]
        self.assertIn("table-chunk-item8-01", chunk_ids)
        self.assertIn("narrative-chunk-item1-01", chunk_ids)
        self.assertIn("narrative-chunk-item7-01", chunk_ids)
        self.assertIn("narrative-chunk-item1a-01", chunk_ids)

    def test_03_partial_synthesis_with_year_substitution(self):
        """Verify synthesis in Fast-Path DCF mode with year substitution flag."""
        audit = _create_mock_audit()
        forecast = _create_mock_forecast()
        dcf = _create_mock_dcf()

        report = self.synthesizer.synthesize(
            ticker="AAPL",
            company_name="Apple Inc.",
            fiscal_year=2025,
            financial_audit=audit,
            forecast=forecast,
            dcf_valuation=dcf,
            year_substituted=True,
        )

        self.assertIsInstance(report, Final10KResearchReport)
        self.assertEqual(report.implied_fair_value_per_share, 245.50)
        self.assertEqual(report.year_substituted, True)
        self.assertIn("Filing Provenance Note", report.full_markdown_report)
        self.assertIn("## Executive Valuation Dashboard", report.full_markdown_report)
        self.assertIn("## 4. Audited Financial Statements & Ratio Performance", report.full_markdown_report)
        self.assertIn("## 6. Discounted Cash Flow (DCF) Valuation & Sensitivity", report.full_markdown_report)

    def test_04_exhaustive_none_guard_resilience(self):
        """Verify _fmt helper gracefully handles None, NaN, and Inf without TypeError exceptions."""
        fmt = LeadSynthesizerAgent._fmt
        self.assertEqual(fmt(None, ".1f"), "N/A")
        self.assertEqual(fmt(float("nan"), ".1f"), "N/A")
        self.assertEqual(fmt(float("inf"), ".1f"), "N/A")
        self.assertEqual(fmt(12.345, ".1f", suffix="%"), "12.3%")
        self.assertEqual(fmt(1234.56, ",.1f", prefix="$", suffix="M"), "$1,234.6M")

    def test_05_run_agent_output_interface(self):
        """Verify BaseAgent.run() interface compatibility for LeadSynthesizer."""
        output = self.synthesizer.run([
            {"role": "user", "content": "Generate final report for Apple"}
        ])
        self.assertIn("LeadSynthesizerAgent", output.content)


if __name__ == "__main__":
    unittest.main()
